### ISSUE TITLE
Feature request: command to generate diagram from DB

### ISSUE THREAD

**Issue by dkdndes** [sageteamorg/django-sage-painless#12]
The dumpdata command allows the generation of data that can be imported via fixtures. The structure is very similar, and could work as a starting point.

Example in the Django docs for [fixtures](https://docs.djangoproject.com/en/4.0/howto/initial-data/#providing-data-with-fixtures), and the [inspectdb](https://github.com/django/django/blob/main/django/core/management/commands/inspectdb.py) command.

As an example, though, here’s what a fixture for a Person model might look like in JSON:

```
[
  {
    "model": "myapp.person",
    "pk": 1,
    "fields": {
      "first_name": "John",
      "last_name": "Lennon"
    }
  },
  {
    "model": "myapp.person",
    "pk": 2,
    "fields": {
      "first_name": "Paul",
      "last_name": "McCartney"
    }
  }
]
```

And here’s that same fixture as YAML:

```
- model: myapp.person
  pk: 1
  fields:
    first_name: John
    last_name: Lennon
- model: myapp.person
  pk: 2
  fields:
    first_name: Paul
    last_name: McCartney
```
